### PR TITLE
Fixing MediaPlayer warnings;

### LINKED ISSUE #586: Getting warnings from MediaPlayer
#### Description of the problem:
Getting the following warnings from MediaPlayer class after scanning a barcode using continuous scan.
```
W/MediaPlayer: Use of stream types is deprecated for operations other than volume control
W/MediaPlayer: mediaplayer went away with unhandled events
```

**Which library version are you using?**
4.1.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Emulator, Android 11.0

**Does the same happen on other devices or an emulator?**
Yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Yes

**In the case of an error do you have a stack trace or adb logs?**
N/A

### PR DESCRIPTION
**Pull request by ANewGalaxy**
Closes #586. I fixed the warnings I was getting related to MediaPlayer/BeepManager:
```
W/MediaPlayer: Use of stream types is deprecated for operations other than volume control
W/MediaPlayer: mediaplayer went away with unhandled events
```

### CODE REVIEW

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java [hunk 1]
```diff
@@ -94,23 +94,20 @@ public synchronized void playBeepSoundAndVibrate() {
...
         MediaPlayer mediaPlayer = new MediaPlayer();
-        mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
-        mediaPlayer.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
-            @Override
-            public void onCompletion(MediaPlayer mp) {
-                mp.stop();
-                mp.release();
-            }
+        mediaPlayer.setAudioAttributes(new AudioAttributes.Builder().setContentType(
+                AudioAttributes.CONTENT_TYPE_MUSIC).build());
```
Comment (ANewGalaxy) [inline zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:98]: Fixes warning: W/MediaPlayer: Use of stream types is deprecated for operations other than volume control

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java [hunk 2]
```diff
@@ -94,23 +94,20 @@ public synchronized void playBeepSoundAndVibrate() {
 
     public MediaPlayer playBeepSound() {
         MediaPlayer mediaPlayer = new MediaPlayer();
-        mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
```
Comment (ANewGalaxy) [inline zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:97]: Removed this line since it is a deprecated method

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java [hunk 3]
```diff
@@ -94,23 +94,20 @@ public synchronized void playBeepSoundAndVibrate() {
...
-            @Override
-            public void onCompletion(MediaPlayer mp) {
-                mp.stop();
-                mp.release();
-            }
+        mediaPlayer.setAudioAttributes(new AudioAttributes.Builder().setContentType(
+                AudioAttributes.CONTENT_TYPE_MUSIC).build());
+        mediaPlayer.setOnCompletionListener(mp -> {
+            mp.stop();
+            mp.reset();
```
Comment (ANewGalaxy) [inline zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:101]: Calling reset before release should fix the following warning: W/MediaPlayer: mediaplayer went away with unhandled events

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java [hunk 4]
```diff
@@ -20,12 +20,12 @@
 import android.app.Activity;
 import android.content.Context;
 import android.content.res.AssetFileDescriptor;
+import android.media.AudioAttributes;
 import android.media.AudioManager;
 import android.media.MediaPlayer;
 import android.os.Vibrator;
 import android.util.Log;
 
-import java.io.Closeable;
```
Comment (ANewGalaxy) [inline zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:28]: Unused import

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java [hunk 5]
```diff
@@ -94,23 +94,20 @@ public synchronized void playBeepSoundAndVibrate() {
...
-        mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
-        mediaPlayer.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
-            @Override
-            public void onCompletion(MediaPlayer mp) {
-                mp.stop();
-                mp.release();
-            }
+        mediaPlayer.setAudioAttributes(new AudioAttributes.Builder().setContentType(
+                AudioAttributes.CONTENT_TYPE_MUSIC).build());
+        mediaPlayer.setOnCompletionListener(mp -> {
```
Comment (ANewGalaxy) [inline zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:99]: Converted this to a lambda

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java [hunk 6]
```diff
@@ -94,23 +94,20 @@ public synchronized void playBeepSoundAndVibrate() {
...
-        mediaPlayer.setOnErrorListener(new MediaPlayer.OnErrorListener() {
-            @Override
-            public boolean onError(MediaPlayer mp, int what, int extra) {
-                Log.w(TAG, "Failed to beep " + what + ", " + extra);
-                // possibly media player error, so release and recreate
-                mp.stop();
-                mp.release();
-                return true;
-            }
+        mediaPlayer.setOnErrorListener((mp, what, extra) -> {
```
Comment (ANewGalaxy) [inline zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:104]: Converted to a lambda

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java [hunk 7]
```diff
@@ -94,23 +94,20 @@ public synchronized void playBeepSoundAndVibrate() {
...
+        mediaPlayer.setAudioAttributes(new AudioAttributes.Builder().setContentType(
+                AudioAttributes.CONTENT_TYPE_MUSIC).build());
+        mediaPlayer.setOnCompletionListener(mp -> {
+            mp.stop();
+            mp.reset();
+            mp.release();
         });
-        mediaPlayer.setOnErrorListener(new MediaPlayer.OnErrorListener() {
-            @Override
-            public boolean onError(MediaPlayer mp, int what, int extra) {
```
Comment (ANewGalaxy) [inline zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:107]: Replaced this with a lambda

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java [hunk 8]
```diff
@@ -94,23 +94,20 @@ public synchronized void playBeepSoundAndVibrate() {
 
     public MediaPlayer playBeepSound() {
         MediaPlayer mediaPlayer = new MediaPlayer();
-        mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
-        mediaPlayer.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
-            @Override
-            public void onCompletion(MediaPlayer mp) {
```
Comment (ANewGalaxy) [inline zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:100]: Replaced with lambda

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java [hunk 9]
```diff
@@ -94,23 +94,20 @@ public synchronized void playBeepSoundAndVibrate() {
...
-                mp.stop();
-                mp.release();
-            }
+        mediaPlayer.setAudioAttributes(new AudioAttributes.Builder().setContentType(
+                AudioAttributes.CONTENT_TYPE_MUSIC).build());
+        mediaPlayer.setOnCompletionListener(mp -> {
+            mp.stop();
+            mp.reset();
+            mp.release();
```
Comment (ANewGalaxy) [inline zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:102]: Calling reset before release should fix the following warning: `W/MediaPlayer: mediaplayer went away with unhandled events`

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java [hunk 10]
```diff
@@ -125,6 +122,7 @@ public boolean onError(MediaPlayer mp, int what, int extra) {
             return mediaPlayer;
         } catch (IOException ioe) {
             Log.w(TAG, ioe);
+            mediaPlayer.reset();
             mediaPlayer.release();
```
Comment (ANewGalaxy) [inline zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:126]: Calling reset before release should fix the following warning: `W/MediaPlayer: mediaplayer went away with unhandled events`

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java (hunk 9 above)
Comment (ANewGalaxy) [inline zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:102]: Calling reset before release should fix the following warning: `W/MediaPlayer: mediaplayer went away with unhandled events`

**Comment by rkistner** [comment]
Thanks for the work - will get this out in the next release.

File: zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java (hunk 1 above)
Comment (ShivamPokhriyal) [reply zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:98]: This is causing crashes in Android 4 devices(4.4.2 and 4.4.4). 
[AudioAttributes](https://developer.android.com/reference/android/media/AudioAttributes) was added in API level 21. 

StackTrace: 
```
Fatal Exception: java.lang.NoClassDefFoundError: android.media.AudioAttributes$Builder
       at com.google.zxing.client.android.BeepManager.playBeepSound(BeepManager.java:97)
       at com.google.zxing.client.android.BeepManager.playBeepSoundAndVibrate(BeepManager.java:84)
       at com.journeyapps.barcodescanner.CaptureManager$1.barcodeResult(CaptureManager.java:80)
       at com.journeyapps.barcodescanner.DecoratedBarcodeView$WrappedCallback.barcodeResult(DecoratedBarcodeView.java:50)
       at com.journeyapps.barcodescanner.BarcodeView$1.handleMessage(BarcodeView.java:52)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Comment (ShivamPokhriyal) [reply zxing-android-embedded/src/com/google/zxing/client/android/BeepManager.java:98]: @ANewGalaxy @rkistner
